#!/bin/sh

# Node 'EZB Detmold'
# Install RSA Key

# install FFLIP RSA key
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAoLa9+XqAM6q2/uU6A510M+QiaFbF8UYY4B+jxFjHQS9SVyWEPjiC0/0aHPhUx2PtlsqeEchxiPk/h77dixQUVZ3jrAaCOvl6i1hCCKZPPI6NMIzuHX5M+SqJMkVTY02QCzqU8ZoZghndVTViO3u2plXGg12jtV2Mqyu2GCDBOji4X0TCsmDo3ridxq5CiqNmpN0DlxGA2wkrlyB2V8akwKpwS7y4FZC81ILTi/FFQgtkYBElOciIkQ2CLVzvVb1rLqNkqoR8EzCCZ0TfrGdHzZz+KTwyW0azrf7UWiiHd++kPdEr5tL6KjctnmpdlUJ8unD2ZNHd7OddahTB/a6eSQ==" >> /etc/dropbear/authorized_keys

# install Kreis Lippe RSA key
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtU+81s2yW/9zDxln9qdTOdozRophKBEfPA4p4NSkjUZ59oYKxCs2NrhXZc85OEj00BVcaf4/cQ38e37GC6+EhOsWGXQyJH5IsYc2kWvyg7XnWlPI+QcQ7JBw3BVRFSzd3JGKQelZuubdHs5R+WueyhbmLIDmH0o7S0O6ZYob//VPDEHt90c/gZ36xoQ5xwQtVUrruKTC4tOFFUwpNVNbQ090PWeV6+Lp22nJlk7UAswyioz3m0ZPkvaBXi9/AeN7Jn8sSCXJxp7wzuJAPC8zTXDpBNv4m9iJkMYwwRuc8acRZ1YM/XSwVVw+FWws0njPjbz9+rKvjw8LGRJYBs8fAw==" >> /etc/dropbear/authorized_keys

# restart ssh daemon
/etc/init.d/dropbear restart

