#!/bin/sh

# Node 'Hexenbürgermeisterhaus'
# Block clients due to FFLIP fair use policy

# set macfilter
uci set wireless.client_radio0.macfilter='deny'
uci set wireless.client_radio0.maclist='5c:51:4f:54:6b:77'
uci set wireless.client_radio1.macfilter='deny'
uci set wireless.client_radio1.maclist='5c:51:4f:54:6b:77'
uci commit
wifi
