#!/bin/sh

# Node 'Liebrecht_Lage_3' hostfile for changing node settings

# Repair domain configuration for this node
 uci set gluon.core.domain='d2lip'
 uci commit
 wget http://update.freifunk-lippe.de/treatment/gluon-fflip-1.0.3-20180927-tp-link-tl-wa901n-nd-v2-sysupgrade.bin -O /tmp/gluon-fflip-1.0.3-20180927-tp-link-tl-wa901n-nd-v2-sysupgrade.bin
 sysupgrade /tmp/gluon-fflip-1.0.3-20180927-tp-link-tl-wa901n-nd-v2-sysupgrade.bin