#!/bin/sh

# Node 'DT STE 9-3' hostfile for changing node settings

# Configure customized SSH access key for this node
wget http://update.freifunk-lippe.de/cronjobs/uhlstonekey/authorized_keys -P /etc/dropbear/
reboot
