#!/bin/sh

# Node 'LemgoDigital (Querbeet)'
# Install FFLIP RSA Key for Lemgo

# install key
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhmSVf09nspZ5wmFaMHK5voM907WX76ipwsk7MW3hR20r28EatRvPeFbOKMz4hAKQtYJsX0wzAUN+EGHWgNIQkGA0fhottMcZOWy/9xwRrkwP9gT6mQ3eIwCFS/Cc7m6BqBOZYkeZC1p90/ZW7FTxVxzOHAV4cCXmpQS96bh3EVUoVCes3OQYHFOXoePE3euWFpG2LOR2BSH+sdAh307TzHNSOuZBfiklMyajJK1g7td7UVtmZ0IZYOgz1AUYzDvqmmlktfEJ/lbD6PXpl/dJLG95MovTQVm5XTA5YTn3Kg+C+tBMRnt5VutwpxJ6bb1dxs8R6w4EOGFM9AMWJ6cVlQ==
" >> /etc/dropbear/authorized_keys
/etc/init.d/dropbear restart

