#!/bin/sh

# Example hostfile for changing nodes settings
# Node FF-MO-ev-Kirchengemeinde-Hochstrass-01

# force branch switch, nice if you want to remove old branches completly
uci set autoupdater.settings.branch=stable
uci commit
